project_id = "tai-chinh-ca-nhan"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
enable_anonymous_sign_ins = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m"
otp_length = 8

[functions.sepay-webhook]
verify_jwt = false

[functions.sepay-sync]
verify_jwt = true
