export const MAX_BODY_BYTES = 256 * 1024;
export const MAX_CLOCK_SKEW_SECONDS = 300;
export type SePayWebhookPayload = { id:number|string; gateway:string; transactionDate:string; accountNumber:string; subAccount?:string; code?:string|null; content:string; transferType:"in"|"out"; transferAmount:number; accumulated?:number; referenceCode?:string };
const encoder=new TextEncoder();
const hex=(bytes:Uint8Array)=>[...bytes].map(v=>v.toString(16).padStart(2,"0")).join("");
export function constantTimeEqual(left:string,right:string):boolean { const a=encoder.encode(left),b=encoder.encode(right);let difference=a.length^b.length;const length=Math.max(a.length,b.length);for(let i=0;i<length;i++)difference|=(a[i%a.length]??0)^(b[i%b.length]??0);return difference===0; }
export async function sha256(value:string):Promise<string>{return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value))));}
export async function hmacSignature(secret:string,timestamp:string,rawBody:string):Promise<string>{const key=await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const signature=await crypto.subtle.sign("HMAC",key,encoder.encode(`${timestamp}.${rawBody}`));return `sha256=${hex(new Uint8Array(signature))}`;}
export async function verifyHmac(secret:string,timestamp:string|null,supplied:string|null,rawBody:string,nowSeconds=Math.floor(Date.now()/1000)):Promise<boolean>{if(!timestamp||!supplied||!/^\d+$/.test(timestamp)||!/^sha256=[0-9a-f]{64}$/i.test(supplied))return false;if(Math.abs(nowSeconds-Number(timestamp))>MAX_CLOCK_SKEW_SECONDS)return false;return constantTimeEqual(await hmacSignature(secret,timestamp,rawBody),supplied.toLowerCase());}
export function parseWebhookPayload(rawBody:string):SePayWebhookPayload{const value=JSON.parse(rawBody) as Record<string,unknown>;if((typeof value.id!=="number"&&typeof value.id!=="string")||String(value.id).trim()==="")throw new Error("INVALID_ID");if(value.transferType!=="in"&&value.transferType!=="out")throw new Error("INVALID_TRANSFER_TYPE");if(!Number.isSafeInteger(value.transferAmount)||Number(value.transferAmount)<=0)throw new Error("INVALID_AMOUNT");for(const field of ["gateway","transactionDate","accountNumber","content"])if(typeof value[field]!=="string"||String(value[field]).trim()==="")throw new Error(`INVALID_${field.toUpperCase()}`);return value as SePayWebhookPayload;}
export function sePayDateToIso(value:string):string{const match=/^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})$/.exec(value);if(!match)throw new Error("INVALID_TRANSACTION_DATE");return `${match[1]}-${match[2]}-${match[3]}T${match[4]}:${match[5]}:${match[6]}+07:00`;}
