@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
package vn.personalfinance.presentation.screen

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import vn.personalfinance.domain.model.*
import vn.personalfinance.domain.repository.DebtInput
import vn.personalfinance.presentation.*
import java.time.LocalDate
import java.time.temporal.ChronoUnit

@Composable fun DebtListScreen(state:FinanceUiState,onRetry:()->Unit,onSort:(DebtSort)->Unit,onAdd:()->Unit,onOpen:(String)->Unit){
 val today=LocalDate.now(VietnamZone);val monthStart=today.withDayOfMonth(1);val monthEnd=monthStart.withDayOfMonth(monthStart.lengthOfMonth())
 val active=state.snapshot.debts.filter{it.status!="paid"};val paid=state.snapshot.debts.filter{it.status=="paid"}
 val monthDue=state.snapshot.installments.filter{!it.dueDate.isBefore(monthStart)&&!it.dueDate.isAfter(monthEnd)}.sumOf{it.totalDue-it.paidAmount}
 val overdue=state.snapshot.installments.filter{it.dueDate<today&&it.paidAmount<it.totalDue}.sumOf{it.totalDue-it.paidAmount}
 val sorted=active.sortedWith(when(state.debtSort){DebtSort.DUE_DATE->compareBy(nullsLast()){it.nextDueDate};DebtSort.BALANCE->compareByDescending{it.currentPrincipal};DebtSort.RISK->compareByDescending<Debt>{d->state.snapshot.installments.count{it.debtId==d.id&&it.dueDate<today&&it.paidAmount<it.totalDue}}.thenBy{it.nextDueDate}})
 ScreenState(state.loading,state.error,false,onRetry){LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
  item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Text("Khoản nợ",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Button(onAdd,Modifier.heightIn(min=48.dp)){Text("＋ Tạo")}};DebtMetrics(active.sumOf{it.currentPrincipal},state.snapshot.debts.sumOf{it.originalPrincipal},monthDue,overdue);Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){DebtSort.entries.forEach{sort->FilterChip(state.debtSort==sort,{onSort(sort)},{Text(when(sort){DebtSort.DUE_DATE->"Gần hạn";DebtSort.BALANCE->"Dư nợ";DebtSort.RISK->"Rủi ro"})})}};Text("Đang hoạt động",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)}
  if(sorted.isEmpty())item{Text("Không có khoản nợ đang hoạt động")};items(sorted,key={it.id}){DebtCard(it,state.snapshot.installments.filter{i->i.debtId==it.id},today){onOpen(it.id)}}
  item{Text("Đã tất toán",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};if(paid.isEmpty())item{Text("Chưa có khoản đã tất toán")};items(paid,key={it.id}){DebtCard(it,emptyList(),today){onOpen(it.id)}}
 }}
}
@Composable private fun DebtMetrics(balance:Long,original:Long,month:Long,overdue:Long){Column(verticalArrangement=Arrangement.spacedBy(6.dp)){listOf("Tổng dư nợ" to balance,"Gốc ban đầu" to original,"Phải trả tháng này" to month,"Đã quá hạn" to overdue).chunked(2).forEach{r->Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){r.forEach{(l,v)->Card(Modifier.weight(1f)){Column(Modifier.padding(10.dp)){Text(l,style=MaterialTheme.typography.labelMedium);Text(v.toVnd(),fontWeight=FontWeight.Bold,color=if(l.contains("quá hạn"))MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.primary)}}}}}}
}
@Composable private fun DebtCard(debt:Debt,installments:List<DebtInstallment>,today:LocalDate,onClick:()->Unit){val late=installments.any{it.dueDate<today&&it.paidAmount<it.totalDue};Card(onClick=onClick){Column(Modifier.fillMaxWidth().padding(14.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(debt.name,fontWeight=FontWeight.Bold);Text(debt.currentPrincipal.toVnd(),fontWeight=FontWeight.Bold)};Text(debt.lenderName?:"Không ghi bên cho vay");Text((if(late)"⚠ Quá hạn" else if(debt.status=="paid")"✓ Đã tất toán" else "⏱ Kỳ tới: ${debt.nextDueDate?:"Chưa đặt"}"),color=if(late)MaterialTheme.colorScheme.error else LocalContentColor.current)}}
}

@Composable fun CreateDebtScreen(saving:Boolean,error:String?,onBack:()->Unit,onSave:(DebtInput)->Unit){var name by remember{mutableStateOf("")};var lender by remember{mutableStateOf("")};var type by remember{mutableStateOf("loan")};var original by remember{mutableStateOf("")};var current by remember{mutableStateOf("")};var hasInterest by remember{mutableStateOf(false)};var rate by remember{mutableStateOf("")};var interestType by remember{mutableStateOf("yearly")};var start by remember{mutableStateOf(LocalDate.now(VietnamZone).toString())};var maturity by remember{mutableStateOf("")};var frequency by remember{mutableStateOf("monthly")};var expected by remember{mutableStateOf("")};var nextDue by remember{mutableStateOf(LocalDate.now(VietnamZone).plusMonths(1).toString())};var note by remember{mutableStateOf("")};var validation by remember{mutableStateOf<String?>(null)}
 Scaffold(topBar={TopAppBar({Text("Tạo khoản nợ")},navigationIcon={TextButton(onBack){Text("‹ Quay lại")}})}){padding->LazyColumn(Modifier.padding(padding).fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
  item{OutlinedTextField(name,{name=it},Modifier.fillMaxWidth(),label={Text("Tên khoản nợ")});OutlinedTextField(lender,{lender=it},Modifier.fillMaxWidth(),label={Text("Bên cho vay")});ChoicePicker("Loại khoản nợ",listOf("loan" to "Khoản vay","credit_card" to "Thẻ tín dụng","mortgage" to "Thế chấp","installment" to "Trả góp","personal" to "Cá nhân","other" to "Khác"),type){type=it}}
  item{MoneyField("Số tiền gốc",original){original=it};MoneyField("Dư nợ hiện tại",current){current=it}}
  item{Row(verticalAlignment=Alignment.CenterVertically){Switch(hasInterest,{hasInterest=it});Text(if(hasInterest)" Có tính lãi" else " Không lãi")};if(hasInterest){OutlinedTextField(rate,{rate=it.filter{c->c.isDigit()||c=='.'}},Modifier.fillMaxWidth(),label={Text("Lãi suất %")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Decimal));ChoicePicker("Cách tính lãi",listOf("monthly" to "Theo tháng","yearly" to "Theo năm"),interestType){interestType=it}}}
  item{DateField("Ngày bắt đầu",start){start=it};DateField("Ngày đáo hạn (có thể trống)",maturity){maturity=it};ChoicePicker("Chu kỳ trả",listOf("weekly" to "Hàng tuần","monthly" to "Hàng tháng","quarterly" to "Hàng quý","yearly" to "Hàng năm","irregular" to "Không định kỳ"),frequency){frequency=it};MoneyField("Số tiền trả dự kiến mỗi kỳ",expected){expected=it};DateField("Ngày đến hạn tiếp theo",nextDue){nextDue=it};OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Ghi chú")})}
  item{(validation?:error)?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button(enabled=!saving,onClick={val o=original.toLongOrNull();val c=current.toLongOrNull();val e=expected.toLongOrNull();val s=runCatching{LocalDate.parse(start)}.getOrNull();val due=runCatching{LocalDate.parse(nextDue)}.getOrNull();val mat=maturity.ifBlank{null}?.let{runCatching{LocalDate.parse(it)}.getOrNull()};validation=when{name.isBlank()->"Nhập tên khoản nợ";o==null||o<=0->"Tiền gốc phải lớn hơn 0";c==null||c<0||c>o->"Dư nợ không hợp lệ";e==null||e<=0->"Khoản trả dự kiến phải lớn hơn 0";s==null||due==null->"Ngày không hợp lệ";hasInterest&&rate.toDoubleOrNull()==null->"Lãi suất không hợp lệ";else->null};if(validation==null)onSave(DebtInput(name,lender,type,o!!,c!!,if(hasInterest)rate.toDouble() else null,if(hasInterest)interestType else "none",s!!,mat,frequency,e!!,due!!,note.ifBlank{null}))},modifier=Modifier.fillMaxWidth().heightIn(min=52.dp)){Text(if(saving)"Đang lưu…" else "Tạo khoản nợ và lịch trả")}}
 }}
}

@Composable fun DebtDetailScreen(debt:Debt?,snapshot:FinanceSnapshot,onBack:()->Unit,onPay:(String,String,Long,Boolean)->Unit,onReverse:(String)->Unit,onSettle:(String)->Unit,onEdit:(String,LocalDate,Long,Long,Long)->Unit){if(debt==null){ScreenState(false,"Không tìm thấy khoản nợ",false,onBack){};return};val today=LocalDate.now(VietnamZone);val installments=snapshot.installments.filter{it.debtId==debt.id}.sortedBy{it.dueDate};val payments=snapshot.debtPayments.filter{it.debtId==debt.id&&it.reversedAt==null}.sortedByDescending{it.createdAt};var payInstallment by remember{mutableStateOf<DebtInstallment?>(null)};var editInstallment by remember{mutableStateOf<DebtInstallment?>(null)};var confirmSettle by remember{mutableStateOf(false)};val totalPaid=payments.sumOf{it.totalPaid};val progress=if(debt.originalPrincipal==0L)0f else ((debt.originalPrincipal-debt.currentPrincipal).toFloat()/debt.originalPrincipal).coerceIn(0f,1f)
 Scaffold(topBar={TopAppBar({Text(debt.name)},navigationIcon={TextButton(onBack){Text("‹ Quay lại")}})}){padding->LazyColumn(Modifier.padding(padding).fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
  item{Card{Column(Modifier.padding(16.dp)){DetailLine("Gốc ban đầu",debt.originalPrincipal.toVnd());DetailLine("Gốc còn lại",debt.currentPrincipal.toVnd());DetailLine("Tổng đã trả",totalPaid.toVnd());LinearProgressIndicator({progress},Modifier.fillMaxWidth().semantics{contentDescription="Tiến độ trả nợ ${(progress*100).toInt()} phần trăm"});Text("Đã trả ${(progress*100).toInt()}% tiền gốc");debt.nextDueDate?.let{val days=ChronoUnit.DAYS.between(today,it);Text(if(days<0)"⚠ Quá hạn ${-days} ngày" else "Còn $days ngày đến kỳ tiếp theo",color=if(days<0)MaterialTheme.colorScheme.error else LocalContentColor.current)};if(debt.currentPrincipal==0L&&debt.status!="paid")Button({confirmSettle=true}){Text("Xác nhận tất toán")}}};Text("Lịch thanh toán",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)}
  items(installments,key={it.id}){i->InstallmentCard(i,today,{payInstallment=i}){editInstallment=i}}
  item{Text("Lịch sử thanh toán",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};if(payments.isEmpty())item{Text("Chưa có thanh toán")};items(payments,key={it.id}){p->Card{Column(Modifier.padding(12.dp)){Text("${p.totalPaid.toVnd()} • ${p.createdAt.atZone(VietnamZone).toLocalDate()}",fontWeight=FontWeight.Bold);Text("Gốc ${p.principalPaid.toVnd()} • Lãi ${p.interestPaid.toVnd()} • Phí ${p.feePaid.toVnd()}"+(if(p.advancePrincipal>0)" • Trả trước ${p.advancePrincipal.toVnd()}" else ""));TextButton({onReverse(p.transactionId)}){Text("Hoàn tác thanh toán")}}}}
 }};payInstallment?.let{i->DebtPaymentDialog(i,snapshot.accounts,{payInstallment=null}){account,amount,advance->onPay(i.id,account,amount,advance);payInstallment=null}};editInstallment?.let{i->EditInstallmentDialog(i,{editInstallment=null}){due,p,interest,fee->onEdit(i.id,due,p,interest,fee);editInstallment=null}};if(confirmSettle)AlertDialog({confirmSettle=false},title={Text("Xác nhận tất toán?")},text={Text("Thao tác này chỉ đổi trạng thái sau khi dư nợ gốc bằng 0.")},confirmButton={Button({onSettle(debt.id);confirmSettle=false}){Text("Tất toán")}},dismissButton={TextButton({confirmSettle=false}){Text("Hủy")}})
}
@Composable private fun InstallmentCard(i:DebtInstallment,today:LocalDate,onPay:()->Unit,onEdit:()->Unit){val remaining=i.totalDue-i.paidAmount;val late=i.dueDate<today&&remaining>0;Card{Column(Modifier.padding(12.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Kỳ ${i.dueDate}",fontWeight=FontWeight.Bold);Text(if(late)"⚠ Quá hạn" else when(i.status){"paid"->"✓ Đã trả";"partially_paid"->"◐ Trả một phần";else->"Sắp tới"},color=if(late)MaterialTheme.colorScheme.error else LocalContentColor.current)};Text("Gốc ${i.principalAmount.toVnd()} • Lãi ${i.interestAmount.toVnd()} • Phí ${i.feeAmount.toVnd()}");Text("Còn phải trả ${remaining.toVnd()}");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){if(remaining>0)Button(onPay,Modifier.heightIn(min=48.dp)){Text("Ghi nhận trả nợ")};TextButton(onEdit,Modifier.heightIn(min=48.dp)){Text("Chỉnh kỳ")}}}}}
@Composable private fun EditInstallmentDialog(i:DebtInstallment,onDismiss:()->Unit,onSave:(LocalDate,Long,Long,Long)->Unit){var due by remember{mutableStateOf(i.dueDate.toString())};var principal by remember{mutableStateOf(i.principalAmount.toString())};var interest by remember{mutableStateOf(i.interestAmount.toString())};var fee by remember{mutableStateOf(i.feeAmount.toString())};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=onDismiss,title={Text("Chỉnh kỳ thanh toán")},text={Column{DateField("Ngày đến hạn",due){due=it};MoneyField("Tiền gốc",principal){principal=it};MoneyField("Tiền lãi",interest){interest=it};MoneyField("Phí",fee){fee=it};error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={Button({val d=runCatching{LocalDate.parse(due)}.getOrNull();val p=principal.toLongOrNull();val n=interest.toLongOrNull();val f=fee.toLongOrNull();error=if(d==null||p==null||n==null||f==null||p+n+f<i.paidAmount)"Tổng kỳ không được thấp hơn số đã trả" else null;if(error==null)onSave(d!!,p!!,n!!,f!!)}){Text("Lưu")}},dismissButton={TextButton(onDismiss){Text("Hủy")}})}
@Composable private fun DebtPaymentDialog(i:DebtInstallment,accounts:List<FinancialAccount>,onDismiss:()->Unit,onSave:(String,Long,Boolean)->Unit){var account by remember{mutableStateOf("")};var amount by remember{mutableStateOf("")};var advance by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)};val remaining=i.totalDue-i.paidAmount;AlertDialog(onDismissRequest=onDismiss,title={Text("Thanh toán kỳ ${i.dueDate}")},text={Column{ChoicePicker("Tài khoản",accounts.map{it.id to it.name},account){account=it};MoneyField("Số tiền đã trả",amount){amount=it};Row(verticalAlignment=Alignment.CenterVertically){Checkbox(advance,{advance=it});Text("Phần vượt kỳ là trả trước tiền gốc")};Text("Còn lại kỳ này: ${remaining.toVnd()}");error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={Button({val value=amount.toLongOrNull();error=when{account.isBlank()->"Chọn tài khoản";value==null||value<=0->"Số tiền không hợp lệ";value>remaining&&!advance->"Bật lựa chọn trả trước nếu vượt số tiền kỳ";else->null};if(error==null)onSave(account,value!!,advance)}){Text("Ghi nhận")}},dismissButton={TextButton(onDismiss){Text("Hủy")}})}
@Composable private fun ChoicePicker(label:String,items:List<Pair<String,String>>,selected:String,onSelect:(String)->Unit){var open by remember{mutableStateOf(false)};Box{OutlinedButton({open=true},Modifier.fillMaxWidth().heightIn(min=52.dp)){Text("$label: ${items.firstOrNull{it.first==selected}?.second?:"Chọn"} ▾")};DropdownMenu(open,{open=false}){items.forEach{(id,name)->DropdownMenuItem({Text(name)},{onSelect(id);open=false})}}}}
@Composable private fun MoneyField(label:String,value:String,onChange:(String)->Unit)=OutlinedTextField(value,{onChange(it.filter(Char::isDigit).take(18))},Modifier.fillMaxWidth(),label={Text(label)},supportingText={Text(value.toLongOrNull()?.toVnd().orEmpty())},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Number))
@Composable private fun DateField(label:String,value:String,onChange:(String)->Unit)=OutlinedTextField(value,onChange,Modifier.fillMaxWidth(),label={Text(label)})
@Composable private fun DetailLine(label:String,value:String)=Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label);Text(value,fontWeight=FontWeight.Bold)}
