@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
package vn.personalfinance.presentation.screen
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import vn.personalfinance.domain.model.FinancialAccount
import vn.personalfinance.domain.repository.DebtInput
import vn.personalfinance.presentation.VietnamZone
import vn.personalfinance.presentation.components.glass.*
import vn.personalfinance.presentation.theme.LiquidGlassColors
import vn.personalfinance.presentation.toVnd
import java.time.LocalDate
import vn.personalfinance.domain.existingLoanSchedule

@Composable fun CreateDebtScreen(accounts:List<FinancialAccount>,saving:Boolean,error:String?,onBack:()->Unit,onSave:(DebtInput)->Unit){
 var existing by remember{mutableStateOf(true)};var name by remember{mutableStateOf("")};var lender by remember{mutableStateOf("")};var principal by remember{mutableStateOf("")};var account by remember{mutableStateOf("")};var hasInterest by remember{mutableStateOf(true)};var mode by remember{mutableStateOf("principal_interest")};var payment by remember{mutableStateOf("")};var interestPaymentDay by remember{mutableStateOf(LocalDate.now(VietnamZone).dayOfMonth.toString())};var totalPeriods by remember{mutableStateOf("")};var firstDue by remember{mutableStateOf(LocalDate.now(VietnamZone).plusMonths(1).toString())};var principalDue by remember{mutableStateOf("")};var currentPeriodPaid by remember{mutableStateOf(false)};var note by remember{mutableStateOf("")};var validation by remember{mutableStateOf<String?>(null)}
 LaunchedEffect(hasInterest){if(hasInterest&&mode=="principal")mode="principal_interest"}
 Scaffold(containerColor=LiquidGlassColors.Background,topBar={TopAppBar({Text("TẠO KHOẢN VAY",fontWeight=FontWeight.Bold)},navigationIcon={TextButton(onBack){Text("‹ Quay lại")}},colors=TopAppBarDefaults.topAppBarColors(containerColor=LiquidGlassColors.Background))}){pad->LazyColumn(Modifier.padding(pad).fillMaxSize().imePadding(),contentPadding=PaddingValues(16.dp,12.dp,16.dp,120.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){
  item{GlassSegmentedControl(listOf(true to "ĐANG HIỆN CÓ",false to "KHOẢN MỚI"),existing,onSelected={existing=it})}
  item{GlassCard{Text(if(existing)"Nhập số tiền hàng tháng, tổng số kỳ và ngày trả đầu tiên. Ứng dụng sẽ tự tính kỳ hiện tại và số kỳ còn lại." else "Khoản mới sẽ cộng số tiền vay vào tài khoản nhận.",color=LiquidGlassColors.TextSecondary)}}
  item{GlassCard{Field("Tên khoản vay",name){name=it};Field("Đơn vị/người cho vay",lender){lender=it};if(!existing||mode=="interest_only")MoneyField(if(existing)"Dư nợ gốc hiện tại" else "Số tiền vay",principal){principal=it};if(!existing)Choice("Tài khoản nhận tiền",accounts.map{it.id to it.name},account){account=it}}}
  item{GlassCard{Row(verticalAlignment=Alignment.CenterVertically){Switch(hasInterest,{hasInterest=it});Text(if(hasInterest)"Có lãi" else "Không lãi",Modifier.padding(start=8.dp),fontWeight=FontWeight.SemiBold)};Choice("Hình thức thanh toán",buildList{add("principal_interest" to "Trả gốc + lãi");if(!hasInterest)add("principal" to "Trả gốc");if(hasInterest)add("interest_only" to "Trả lãi")},mode){mode=it};Text(when(mode){"interest_only"->"Trả lãi hàng tháng, không giảm nợ gốc. Khi thanh toán vẫn có thể nhập thêm khoản gốc.";"principal"->"Toàn bộ khoản trả sẽ trừ vào tiền vay gốc.";else->"Phần gốc của mỗi kỳ sẽ được trừ trực tiếp vào tiền vay."},style=MaterialTheme.typography.bodySmall,color=LiquidGlassColors.TextSecondary);MoneyField(if(mode=="interest_only")"Tiền lãi trả hàng tháng" else "Số tiền hàng tháng",payment){payment=it}}}
  item{GlassCard{if(mode=="interest_only"){Field("Ngày trả lãi hàng tháng (1–31)",interestPaymentDay,true){interestPaymentDay=it.filter(Char::isDigit).take(2)};DatePickerField("Thời gian trả gốc (không bắt buộc)",principalDue){principalDue=it};Text("Lãi được trả hàng tháng vào ngày đã chọn. Để trống thời gian trả gốc nghĩa là không có hạn trả gốc.",style=MaterialTheme.typography.bodySmall,color=LiquidGlassColors.TextSecondary)}else{Field("Tổng số kỳ",totalPeriods,true){totalPeriods=it.filter(Char::isDigit).take(3)};DatePickerField("Thời gian trả đầu tiên",firstDue){firstDue=it};if(existing)Row(verticalAlignment=Alignment.CenterVertically){Checkbox(currentPeriodPaid,{currentPeriodPaid=it});Text("Kỳ hiện tại đã trả")}};Field("Ghi chú",note){note=it}}}
  item{(validation?:error)?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button(enabled=!saving,onClick={val enteredPrincipal=principal.toLongOrNull();val amount=payment.toLongOrNull();val interestDay=interestPaymentDay.toIntOrNull();val total=if(mode=="interest_only")1 else totalPeriods.toIntOrNull();val enteredDue=runCatching{LocalDate.parse(firstDue)}.getOrNull();val today=LocalDate.now(VietnamZone);val schedule=if(existing&&mode!="interest_only"&&enteredDue!=null&&total!=null&&total>0)existingLoanSchedule(enteredDue,total,today,currentPeriodPaid) else null;val left=if(mode=="interest_only")1 else if(existing)schedule?.remaining else total;val due=if(mode=="interest_only"&&interestDay in 1..31)nextInterestDue(today,interestDay!!) else if(existing)schedule?.nextDue else enteredDue;val p=if(mode=="interest_only")enteredPrincipal else if(existing&&amount!=null&&total!=null)amount*total else enteredPrincipal;val current=if(mode=="interest_only")p else if(existing&&amount!=null&&left!=null)amount*left else p;val payoff=principalDue.ifBlank{null}?.let{runCatching{LocalDate.parse(it)}.getOrNull()};validation=when{name.isBlank()->"Nhập tên khoản vay";(mode=="interest_only"||!existing)&&(p==null||p<=0)->if(existing)"Dư nợ gốc hiện tại phải lớn hơn 0" else "Số tiền vay phải lớn hơn 0";!existing&&account.isBlank()->"Chọn tài khoản nhận tiền";amount==null||amount<=0->"Số tiền hàng tháng phải lớn hơn 0";mode=="interest_only"&&interestDay !in 1..31->"Ngày trả lãi phải từ 1 đến 31";mode!="interest_only"&&(total==null||total<=0)->"Tổng số kỳ phải lớn hơn 0";mode!="interest_only"&&enteredDue==null->"Thời gian trả đầu tiên không hợp lệ";existing&&mode!="interest_only"&&(left==null||left<=0)->"Khoản vay đã hết kỳ theo thời gian thực";principalDue.isNotBlank()&&payoff==null->"Thời gian trả gốc không hợp lệ";mode!="interest_only"&&!existing&&amount*total!!<p!!->"Số tiền hàng tháng × tổng số kỳ chưa đủ số tiền vay";else->null};if(validation==null)onSave(DebtInput(name.trim(),lender.trim(),"loan",p!!,current!!,null,if(hasInterest)"monthly" else "none",today,payoff,"monthly",amount!!,due!!,note.ifBlank{null},if(existing)0 else p,!existing,left,if(existing)null else account,total,mode,currentPeriodPaid))},modifier=Modifier.fillMaxWidth().heightIn(min=54.dp)){Text(if(saving)"ĐANG LƯU…" else "LƯU KHOẢN VAY",fontWeight=FontWeight.Bold)}}
 }}}
private fun nextInterestDue(today:LocalDate,day:Int):LocalDate {
 fun inMonth(date:LocalDate)=date.withDayOfMonth(minOf(day,date.lengthOfMonth()))
 val thisMonth=inMonth(today)
 return if(thisMonth.isAfter(today))thisMonth else inMonth(today.plusMonths(1))
}
@Composable private fun Field(label:String,value:String,numeric:Boolean=false,onChange:(String)->Unit)=OutlinedTextField(value,onChange,Modifier.fillMaxWidth().padding(vertical=4.dp),singleLine=true,label={Text(label)},keyboardOptions=KeyboardOptions(keyboardType=if(numeric)KeyboardType.Number else KeyboardType.Text))
@Composable private fun MoneyField(label:String,value:String,onChange:(String)->Unit)=OutlinedTextField(value,{onChange(it.filter(Char::isDigit).take(18))},Modifier.fillMaxWidth().padding(vertical=4.dp),singleLine=true,label={Text(label)},supportingText={Text(value.toLongOrNull()?.toVnd().orEmpty())},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Number))
@Composable private fun Choice(label:String,items:List<Pair<String,String>>,selected:String,onSelect:(String)->Unit){var open by remember{mutableStateOf(false)};Box{OutlinedButton({open=true},Modifier.fillMaxWidth().heightIn(min=52.dp)){Text("$label: ${items.firstOrNull{it.first==selected}?.second?:"Chọn"}",Modifier.weight(1f),maxLines=1,overflow=TextOverflow.Ellipsis)};DropdownMenu(open,{open=false}){items.forEach{(id,title)->DropdownMenuItem({Text(title)},{onSelect(id);open=false})}}}}
